url: https://atrforum.github.io/transport_research_committee
baseurl:

# Site settings
title: PTRC
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


research_needs:
- text: Suggest a research need we are missing!
  url: https://docs.google.com/forms/d/e/1FAIpQLSc1NWF3mpvbUERh4D35tg2ATgEzn6J4xQX_m-lU484E-tSjAQ/viewform
- text: An ongoing list of research needs suggested by interested parties (researchers, consultants, users, the public etc)
  url: #
- text: An annual survey of authorities responsible for operating and planning public transport in Australasia
  url: #


# Team names, titles and social links
leadership:
- name: Graham Currie
  pic: 1
  position: Chair
  url: #
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

- name: Subeh Chowdhury
  pic: 3
  position: Co-vice chair
  url: #
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

- name: Pedro Camargo
  pic: 2
  position: Co-vice chair
  url: https://www.xl-optim.com/
  social:

    - title: briefcase
      url: https://www.outerloop.io/
    - title: linkedin
      url: https://www.linkedin.com/in/pedrocamargo/

- name: James Reynolds
  pic: 4
  position: Secretary
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

- name: Geoffrey Clifton
  pic: geoff
  position: Research Needs Coordinator
  social:
  # - title: twitter
  #   url: #
  # - title: linkedin
  #   url: #

people:
- name: Hamish Barnet
  pic: hamish
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Kelly Bertolaccini
  pic: kelly
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Euan Brown
  pic: euan
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Jon Bunker
  pic: jonathan
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

- name: Fuad Huda
  pic: fuadh
  position: member
  url: http://publictransportresearchgroup.info/our-team/research-students/fuad-huda/
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/fuad-yasin-huda-39105538/
  - title: university
    url: https://scholar.google.co.uk/citations?user=CykERRoAAAAJ&hl=en

- name: Kathy Lazanas
  pic: 5
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Neema Nassir
  pic: 5
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: John Nelson
  pic: 5
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Peter Newman
  pic: peternewman
  position: member
  url: https://en.wikipedia.org/wiki/Peter_Newman_(environmental_scientist)
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Brendan O'Keeffe
  pic: brendan
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Mark O'Reilly
  pic: 5
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Sekhar Somenahalli
  pic: sekhar
  position: member
  url: https://people.unisa.edu.au/sekhar.somenahalli
  social:
  - title: linkedin
    url: https://people.unisa.edu.au/sekhar.somenahalli
- name: Ian Wallis
  pic: 5
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Adrian Webb
  pic: adrian
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Doug Weir
  pic: dougweir
  position: member
  url: 
  social:
    - title: briefcase
      url: •	https://www.stantec.com/en/people/w/weir-doug
    - title: linkedin
      url: •	https://www.linkedin.com/in/doug-weir-792abbb2/
- name: Ian Woodcock
  pic: ian
  position: member
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #

resources:
  databases:
  - name: Public Transport Research Paper Database of the Australasian Transport Research Form (since 1975)
    url: https://australasiantransportresearchforum.org.au/papers/?sdata=public+transport
  - name: The World Transit Research Clearinghouse
    url: https://www.worldtransitresearch.info/
  - name: Publication Library of the US Transit Cooperative Research Program (TCRP)
    url: https://nap.nationalacademies.org/author/TCRP/transportation-research-board/transit-cooperative-research-program
  - name: Public Transport Research Reports of the NZ Transport Agency (Waka Kotahi)
    url: https://www.nzta.govt.nz/walking-cycling-and-public-transport/public-transport/planning-and-investing-in-public-transport/public-transport-research
  - name: PTRC live list of public transport data resources
    url: https://docs.google.com/spreadsheets/d/1E-M-SUzQu0D6BE9kniDRaitEbBuDDyieQpqCzVS3rOs/edit?gid=0#gid=0

  podcasts:
  - name: Researching Transit
    url: http://publictransportresearchgroup.info/home-creative/podcast/
  - name: The Overhead Wire
    url: https://theoverheadwire.com/
  - name: Transit Unplugged
    url: https://www.transitunplugged.com/
  - name: "Between The Lines: A Metrolinx Podcast"
    url: https://podcasts.apple.com/us/podcast/between-the-lines-a-metrolinx-podcast/id1593439320

  anz_research_centres:
  - name: TRC (University of Auckland)
    url: https://www.auckland.ac.nz/en/engineering/our-research/discover/research-areas-and-facilities/transportation.html
  - name: Public Transport Research Group (Monash University)
    url: http://publictransportresearchgroup.info/
  - name: Institute of Transport and Logistics Studies (Sydney University)
    url: https://www.sydney.edu.au/business/our-research/institute-of-transport-and-logistics-studies.html
    
  other:


upcoming_events:
  - name: 45th ATRF
    location: Melbourne
    date: 27-29 Nov 2024
    url: https://www.atrf2024.com/


  - name: High Speed Rail and Urban Design
    location: Melbourne
    date: 29 Nov 2024
    url: https://www.linkedin.com/feed/update/urn:li:activity:7264471263010578432/?utm_source=share&utm_medium=member_desktop


past_webinars:

  - name: Webinar On-Demand Public Transport in Australia and New Zealand
    url: https://www.youtube.com/watch?v=LKLP65cJL1w
    description: This webinar explores the role of on-demand public transport in Australia and New Zealand. It discusses several case studies with examples from successful public transport operators.

  - name: Trackless Trams - a New Mid-Tier Transit System
    url: https://www.youtube.com/watch?v=_sZ4xpqvIhg
    description: The need for mid-tier transit in Australasian cities is growing as we recognise the role that can be played as a high-capacity connector down main roads and an enabler of urban regeneration around station precincts. This is part of the global process described as a Movement and Place Strategy which was started by TfL. Added to this is the new dimension of net zero. The Webinar will build on a research project at Curtin that has worked with communities, local governments, state agencies and industry (including Stantec) across Australasia, to help better define what can be done to create a Transit Activated Corridor (TAC) or a Net Zero Corridor (NZC). It is globally significant work that has been recognised by groups like the World Economic Forum and the UNFCCC in Sharm El Sheikh at COP 27. Videos, academic papers, industry reports and media have all helped to present the perspective of the three presenters and there has been considerable debate as the concept was applied to Townsville, Liverpool (Syd), Wyndham (Melb), Perth and Bunbury. Two trackless trams are due to arrive in Australia for testing in August and new opportunities are emerging for their application.

  - name: ACADEMICS SUPPORTING ADVOCATES - improving effective collaboration
    url: https://www.youtube.com/watch?v=zbm0bgm2U1c
    description: Many researchers are comfortable assuming the role of advocate. However, this isn`t always possible with constraints often imposed by institutions, funding arrangements or the need to maintain relationships with key stakeholders. Building relationships between academics and advocates can ensure that research, ideas, and findings can reach a broader audience. In this webinar we will explore the role that researchers and academics can play to support public transport advocates to encourage change and build support for new policies or investment, including understanding advocacy and resource limitations, opportunities for research and researchers to support advocacy, and working together to drive change


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/groups/14237600/
  - title: github
    url: https://github.com/atrforum/pt_research_committee

# Build settings
markdown: kramdown
permalink: pretty
